add_boi_eoi: false
align_img_and_speech_tokens_dim: true
encoder_name: siglip_gemma2_448
hf_repo: 'kyutai/moshika-vis-pytorch-bf16'
image_size: 512
interpolation: bicubic
mimi_codec: tokenizer-e351c8d8-checkpoint125.safetensors
model: model.safetensors
norm_extra: null
norm_xa: rms_norm
num_crossattended_tokens: -1
num_extra_tokens: 0
text_tokenizer: tokenizer_spm_32k_3.model
xa_conditional_gating: true
xa_delay: 0
xa_dim: null
xa_start: start
xa_end: end
xa_gate_shared: false
xa_gating: sigmoid
xa_layers: []
xa_shared: true
xa_step: 1